# This is the main configuration file for BuildProtection. You can change the settings here to your liking.
# If you have any questions, feel free to ask in the Discord server: https://discord.gg/7QbJ6j6

#enter_message_type: "message" "action" "none"

#All cost are calculated per block in m3 Area. x*y*z

protection:
  cost_create_per_block: 1
  cost_sell_per_block: 1
  enter_message_type: "message"
  max_height: 100
  max_width: 100
  max_radius: 50
rent:
  cost_per_block: 0.1
  time_in_days: 10
  auto_rent: true
random_teleport:
  min_x_z: 500
  max_x_z: 8000
  cooldown: 1440 #minutes
  last_location_on_cooldown: true #If true, the player can return to the last location using /prote rtp return
  disabled_worlds:
  - "world_nether"
  - "world_the_end"
options:
  no_enter_message_using_elytra: true 
