# This is the main configuration file for BuildProtection. You can change the settings here to your liking.
# If you have any questions, feel free to ask in the Discord server: https://discord.gg/7QbJ6j6

#enter_message_type: "message" "action" "none"

#All cost are calculated per block in m3 Area. x*y*z

protection:
  cost_create_per_block: 1
  cost_sell_per_block: 1
  enter_message_type: "message"
  max_height: 100
  max_width: 100
  max_radius: 50
rent:
  cost_per_block: 0.01
  time_in_days: 15
options:
  no_enter_message_using_elytra: true 
