main: com.ar.askgaming.buildprotection.Main
name: BuildProtection
api-version: 1.21
version: 0.1
author: AMONLY
soft-depend: [Residence]
commands:
  prote:
    aliases: [protection]
    description: Manage dragons in your server.
permissions:
  buildprotection.commands:
    description: Allows the player to use the /protection command.
    default: true
  buildprotection.admin:
    description: Allows Admins control all the protections
    default: op
  buildprotection.teleport:
    description: Allows the player to teleport to the protection
    default: op
  buildprotection.listohers:
    description: Allows the player to list the protections of others
    default: op