main: com.ar.askgaming.buildprotection.BuildProtection
name: BuildProtection
api-version: 1.21
version: 1
author: AMONLY
soft-depend: [Vault, RealisticEconomy]
commands:
  prote:
    aliases: [protection]
    description: Manage dragons in your server.
  rtp:
permissions:
  buildprotection.commands:
    description: Allows the player to use the /protection command.
    default: true
  buildprotection.admin:
    description: Allows Admins control all the protections
    default: op
  buildprotection.teleport:
    description: Allows the player to teleport to the protection
    default: op
  buildprotection.listothers:
    description: Allows the player to list the protections of others
    default: op
  buildprotection.flags.*:
    description: Allows the player change flags
    default: true